### ISSUE TITLE
Cannot get README example to pass

### ISSUE THREAD

**Issue by BryceBeagle** [davidfritzsche/pytest-mypy-testing#10]
Hi I'm trying to get started with using your project, but I can't even get a simple test to pass.

```
$ pytest --verbose
======================================= test session starts =======================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/user/.virtualenvs/virtualenv_name/bin/python
cachedir: .pytest_cache
rootdir: /home/user/project, inifile: pytest.ini
plugins: mypy-testing-0.0.6
collected 1 item                                                                                  

tests/test_example.py::[mypy]mypy_test_invalid_assginment FAILED                            [100%]

============================================ FAILURES =============================================
_______________________________ [mypy]mypy_test_invalid_assginment ________________________________
/home/user/project/tests/test_example.py:7: error (missing): Incompatible types in assignment (expression has type "int", variable has type "str")
======================================== warnings summary =========================================
tests/test_example.py::[mypy]mypy_test_invalid_assginment
  /home/user/.virtualenvs/virtualenv_name/lib/python3.8/distutils/__init__.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================== short test summary info =====================================
FAILED tests/test_example.py::[mypy]mypy_test_invalid_assginment - 
================================== 1 failed, 1 warning in 1.26s ===================================
``` 

where my test file contains just the example from the README:

```python3
import pytest  # type: ignore


@pytest.mark.mypy_testing
def mypy_test_invalid_assginment():
    foo = "abc"
    foo = 123  # E: Incompatible types in assignment (expression has type "int", variable has type "str")
```

Am I missing something vital to use this project?

**Comment by davidfritzsche** [comment]
@BryceBeagle Thank you for reporting the issue. This should now work with version 0.0.7. By default, mypy does not type-check functions that do not have any type annotation, i.e., the `mypy_test_invalid_assignment` function from the README example is not checked by default by mypy. In 0.0.7 I changes the command line arguments to mypy to always say `--check-untyped-defs` to force mypy to type check all functions. I assume that many test functions will be un-annotated.

It "worked" for me since all projects where I use pytest-mypy-testing have `check_untyped_defs = True` in their mypy.ini config.
